---
codacy:
  coverage:
    coverage:
      default: 80

    languages:
      go:
        default: 80

    partials:
      - "**/*_test.go"
      - "**/mocks/**"

    exclude_paths:
      - "docs/**"
      - "cmd/api/**"
      - "bin/**"
      - "**/*_test.go"
      - "internal/database/**"
      - "internal/config/**"
      - "internal/router/**"
      - "internal/handlers/helpers.go"
      - "internal/handlers/webhook.go"
