package docs

import (
	"testing"
)

func TestDocsGenerated(t *testing.T) {
	// docs.go is auto-generated by swaggo/swag
	// This test just ensures the package compiles correctly
	if docTemplate == "" {
		t.Error("docTemplate should not be empty")
	}
	
	// Verify the template contains expected Swagger fields
	if len(docTemplate) == 0 {
		t.Error("docTemplate should contain data")
	}
}
